global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "auth-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: "order-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["order-service:8003"]

  - job_name: "payment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8004"]

  - job_name: "chaos-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["chaos-service:8005"]
